line-length = 100

[format]
quote-style = "double"
indent-style = "space"

[lint]
extend-select = [
  "ANN", # flake8-annotations
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "ERA", # eradicate
  "F",   # Pyflakes
  "I",   # isort
  "ISC", # flake8-implicit-str-concat
  "N",   # pep8-naming
  "PT",  # flake8-pytest-style
  "PYI", # flake8-pyi
  "RET", # flake8-return
  "RUF", # Ruff-specific rules
  "SIM", # flake8-simplify
  "UP",  # pyupgrade
  "W",   # Warning (whitespace)
  "trailing-comma-on-bare-tuple",
]

extend-ignore = [
  "S",   # "flake8-bandit"
  "TRY", # tryceratops
  "any-type",
  "in-dict-keys",
  "line-too-long",
  "lowercase-imported-as-non-lowercase",
  "no-explicit-stacklevel",
  "pytest-incorrect-pytest-import",
  "pytest-raises-too-broad",
  "pytest-raises-with-multiple-statements",
  "redefined-while-unused",
  "redundant-numeric-union",
  "unnecessary-assign",
  "unnecessary-collection-call",
  "useless-import-alias",
]

extend-unfixable = [
  "batched-without-explicit-strict",
  "map-without-explicit-strict",
  "zip-without-explicit-strict",
]
preview = true

[lint.isort]
force-sort-within-sections = true
split-on-trailing-comma = false

[lint.flake8-pytest-style]
parametrize-names-type = "csv"
